# Generated by Django 5.2.7 on 2025-11-10 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('land', 'Terrain'), ('commercial', 'Local commercial')], max_length=20)),
                ('usage', models.CharField(choices=[('primary', 'Résidence principale'), ('secondary', 'Résidence secondaire'), ('rental', 'Investissement locatif')], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('construction_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('occupancy_status', models.CharField(blank=True, max_length=20)),
                ('dpe', models.CharField(blank=True, max_length=5)),
                ('ges', models.CharField(blank=True, max_length=5)),
                ('is_co_owned', models.BooleanField(default=False)),
                ('condo_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_condition', models.CharField(blank=True, max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('loan_duration_months', models.PositiveIntegerField(blank=True, null=True)),
                ('gross_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='properties/documents/')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
        ),
    ]
