# Generated by Django 5.2.7 on 2025-11-11 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_owner_alter_propertydocument_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
    ]
